### ISSUE TITLE
Suncal - v1.6.4 miscalculation

### ISSUE THREAD

**Issue by mnvigil** [sandialabs/suncal#11] opened 2024-02-15 20:10 UTC
Collin, I should start with...Thank you so much for your time creating this app! So nice for teaching the concepts, analysis, and creating procedures! I love it and will undoubtedly use it often as a replacement to risk guard and manual programming.

Comments:

In the Suncal app>Risk Analysis>Full Mode>Integral Calculation:

(1) The Process distribution std does not update when the specification limits are changed. It always assumes the specifications are +/- 1.
(2) Input values are lost when switching between Full and Simple Mode
(3) Use of one sided limits does not calculate properly (for instance by setting the lower spec limit to -INF)
(4) Would be nice to have Cpk/Ppk as an alternate unit to ITP

In the Suncal app>Risk Analysis>Risk Curves:
(1) Print out the max of the curve to verify against the Dobbert whitepapers
(2) I get an error when switching the Guardband Factor, such as 'Dobbert'

**Comment by cdelker** [comment] 2024-02-21 23:05
Thank you for the comments. Most of these items have been updated in version 1.6.5.

1) As-designed. The specification limits and process distribution are independent parameters which can be adjusted separately. Use the "Adjust ITP" button to change the std value to hit a certain ITP.
2) As-designed. Because Simple mode loses information contained in full mode and requires changing the input parameters to simplify, a round trip of values is not possible. 1.6.5 moved the Simple mode elsewhere in preparation for new features planned in 1.7, so the issue is no longer present anyway.
3) Fixed in 1.6.5
4) Added to the list for 1.7

1) Suncal was compared against the Dobbert paper in [this example notebook](https://github.com/sandialabs/suncal/blob/9cf70ea2ad3f389e1de038184a2878478927ba0b/doc/API%20Examples/Risk%20-%20Dobbert%20Guardband%20Derivation.ipynb). I'll consider adding something to the UI, but I'm not sure it's the best place for it due to the time required to calculate points at a high enough resolution.
2) Fixed in 1.6.5.

**Closed by cdelker** 2024-02-21 23:05 UTC

**Comment by mnvigil** [comment] 2024-02-22 17:44
Collin, Excellent! thank you - I know this can be time consuming.

For (1) - because spec limit/ITP/std are mathematically related, changing one changes the others. For instance: 
- If SL=+/-1, ITP = 92% then sd changes to 0.57 in Suncal. Perfect. 
- But if I then change SL=+/-2, std remains 0.57 (but should change to 1.14). 
- Would it possibly be better to have ITP a static field rather than a pop up to see how these three parameters change as the user updates them? 

Apologies for taking your time related to (4) . Just throwing this out there in case you find it useful. 
- I find in practice that people have a preference for describing capability that they are reluctant to change from.
- The five equivalent capability metrics are (1) ITP (% conforming), (2) % non-conforming (3) PPM (4) Sigma level (5) Ppk/Cpk.
- Just something to consider is that your tool may prove most user friendly given the option of allowing a preferred metric.

I didn't see the monte carlo option in the risk module anymore. I hope it can still be there as I find this sometimes helps people understand the method more that the analytical method (using calculus) does possibly because they can see the tangible data points instead of the ideal calculation. In my world, I need to help people understand and use the method rather that just creating a result.

I really love it , Collin. Thank you for the time you put into this and sorry for my incoherent blabbing ;)

**Comment by mnvigil** [comment] 2024-07-22 16:46
Dr. Castrup/Collin,

Thank you for you time helping me work with Suncal and Risk Guard, they are booth very helpful.
If you are able, I would appreciate if I can get your input on something.
With the same inputs in both softwares, I get different outputs for PFA. I'm sure I'm inputting something wrong and wondering can see my error.

Inputs:

  *   Lower spec = 7
  *   ITP=51.77%
  *   Standard Uncertainty = 0.51829
  *   Max risk = 5%

Outputs:
PFA (unconditional/consumer, without guard bands):

  *   Risk Gard: 6.9%
  *   Suncal: 9.3%
Guard band:

  *   Risk Guard: -26.895
  *   Suncal: 0.24232 (relative to spec)

***@***.***

Mario Vigil | Senior DAE / Validation engineer, DfSS GB | ***@***.******@***.***>
Philips Image Guided Therapy Devices, IGTD | www.philips.com/IGTdevices<http://www.philips.com/IGTdevices>
9965 Federal Drive, Colorado Springs, CO  80921 | Mobile: 719.641.5965
